server:
  port: 5000

spring:
  cloud:
    gateway:
      routes:
        - id: employee
          uri: ${EMPLOYEE_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/employee 